### ISSUE TITLE
Cohort Management page shows 0 Patients for all cohorts

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#139]
In the table, there are 0 patients for all cohorts.

**Comment by phyllers** [comment]
Looks like we're not saving patient lists with cohorts. Should this be removed?

**Comment by LoveAndCoding** [comment]
Because we use sample barcodes rather than patient barcodes, this got sort of weird. The number would have been either inaccurate, or a weird mix of patient barcodes and sample barcodes depending on if it is coming from TCGA or if it was uploaded with patient barcodes. But I wasn't sure if the column was there as requirement for something or if it was needed/useful for a particular reason.

**Comment by phyllers** [comment]
Yeah I read the comment and understood. I think this is something I'll have to take up with Sheila. I'll reprioritize for now.

**Comment by phyllers** [comment]
Okay, so Sheila would like to store both. What is the path of least resistance?

Currently, if a user uploads clinical data, we just attribute it to the sample correct? And if there are more than one sample per patient, do we store the duplicate clinical data? I think so, i just want to confirm.

**Comment by rgbohner** [comment]
Shall we assume if no patients barcode then count the sample bar codes are the patients barcode in the cohort list?

**Comment by phyllers** [comment]
I've put in a hack to save participant barcodes from the metadata_data table. Basically if you are NOT using user data/projects, then this will save participant barcodes as normal from the metadata. OTHERWISE, it will not do anything as it was before.
