### ISSUE TITLE
Delete Workbook on workbooks page causes https error

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#180]
This seems to only be an issue on deployment. The deleting a workbook causes a Mixed Content error.

<img width="453" alt="screen shot 2016-02-26 at 9 20 01 am" src="https://cloud.githubusercontent.com/assets/4040084/13359629/22959e12-dc6a-11e5-8843-cec6f6cd5ec7.png">

The workbook _does_ actually get deleted, and the redirect in the view doesn't trigger. So it looks like it doesn't get removed until you refresh the page.

**Comment by rgbohner** [comment]
I am not able to replicate this on the LSDF deployment or locally.  Check the route for workbook delete is not returning any obvious routing issues https://github.com/BlinkUX/ISB-LSDF/blob/master/workbooks/views.py

`if command == "delete":
            redirect_url = reverse('workbooks')
            return redirect(redirect_url)
`
And the workbook delete is occurring via POST rather than AJAX so I'm not sure why you are getting this error.  I made some change to the aria in a bug fix branch.  Please merge I try to reproduce this error

**Comment by phyllers** [comment]
So for some reason, in the workbooks_list.js, it sends the ajax request. However, this should override the default form submission. But based on the the evidence, the page looks like it's somehow sending it twice.

**Comment by phyllers** [comment]
working!
